### ISSUE TITLE
Incorrect output url for rewrite rule with & parameter

### ISSUE THREAD

**Issue by vladimir-reznikov** [madewithlove/htaccess.madewithlove.com#55]
Test URL : http://123.test.ru/js/api555.js
Rewrite rules :
RewriteCond %{HTTP_HOST} ^(www\.)?[^\.]+\.(test\.ru)
RewriteRule ^js/api(.+)\.js$ /api.php?hostname=$1&mode=2 [L]

Output url: http://123.test.ru/api.php%3Fhostname=555test.ru6mode=2
instead of: http://123.test.ru/api.php%3Fhostname=555%26mode=2

The problem is - that after converting '&' char to '%26' it handles '%2' like rewrite rule and inserts second match group.

**Comment by phipps73** [comment]
Has this issue been fixed? I've just tried the following:

https://htaccess.madewithlove.com?share=17693a20-c7d4-477a-85a2-7c0971ce598b

You will see that the output url has put 'oxfordshire' where the %2 of the %26 should be - I'm sure that it will work in apache but would like to see that works before I deploy to our staging env.

**Comment by jdrieghe** [comment]
@phipps73 Thanks for the reminder and the extra test case. We fixed it just now and it looks like the target URL is behaving as expected now in your provided case.

**Comment by phipps73** [comment]
@jdrieghe I can confirm that it is now working correctly - Many thanks for the fix!
