### ISSUE TITLE
Back-reference to the RewriteRule followed by number

### ISSUE THREAD

**Issue by kajman-cz** [madewithlove/htaccess.madewithlove.com#72]
Back reference $N in RewriteRule target followed by number is translated to Nnumber.

I want to add a zero between the dash and the number 3 in url
http://example.com/dir/file-3.png
by
`RewriteRule ^(.*-)(3\.png)$ $10$2 [R,NE,L]`
the tester says the new url is http://example.com/103.png
the apache says new url is http://example.com/dir/file-03.png

Back reference from RewriteCond %N looks fine. Apache documentation limits $N (N=0..9).

Note: `${1}0$2` works in tester but not in apache

**Comment by WouterSioen** [comment]
Hi,

Thanks for the bug report, we'll look into it! The way apache handles regexes isn't always very clear, but these examples should help us improve our regex handling!
